version: '3.7'

services:
  workstation1:
    build: ./middleware
    container_name: workstation1
    networks:
      assistant_net:
        ipv4_address: 10.0.1.2
    ports:
      - 8081:3000
  workstation2:
    build: ./middleware
    container_name: workstation2
    networks:
      assistant_net:
        ipv4_address: 10.0.1.3
    ports:
      - 8082:3000
  balancer:
    build: ./nginx
    networks:
      assistant_net:
        ipv4_address: 10.0.1.1
    ports:
      - 80:80
    links:
      - workstation1
      - workstation2
networks:
  assistant_net:
    external: true