version: '3.7'

services:
  app1:
    build: ./middleware
    container_name: app1
    networks:
      ats_net:
        ipv4_address: 10.0.1.2
    ports:
      - 8081:3000
  app2:
    build: ./middleware
    container_name: app2
    networks:
      ats_net:
        ipv4_address: 10.0.1.3
    ports:
      - 8082:3000
  balancer:
    build: ./nginx
    networks:
      ats_net:
        ipv4_address: 10.0.1.1
    ports:
      - 80:80
    links:
      - app1
      - app2
networks:
  ats_net:
    external: true